flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
  - cond-0.4.1.1
  - butcher-1.3.1.1
  - czipwith-1.0.1.0
  - data-tree-print-0.1.0.1
  - ghc-exactprint-0.5.6.1
  - monad-memo-0.4.1
  - deque-0.2.1
resolver: lts-9.12
